CREATE TABLE pob AS
SELECT * FROM "01";

INSERT INTO pob
SELECT * FROM "02";
INSERT INTO pob
SELECT * FROM "03_1";
INSERT INTO pob
SELECT * FROM "03_2";
INSERT INTO pob
SELECT * FROM "04";
INSERT INTO pob
SELECT * FROM "05";
INSERT INTO pob
SELECT * FROM "06";
INSERT INTO pob
SELECT * FROM "07";
INSERT INTO pob
SELECT * FROM "08_1";
INSERT INTO pob
SELECT * FROM "08_2";
INSERT INTO pob
SELECT * FROM "09";
INSERT INTO pob
SELECT * FROM "10";
INSERT INTO pob
SELECT * FROM "11";
INSERT INTO pob
SELECT * FROM "12";
INSERT INTO pob
SELECT * FROM "13";
INSERT INTO pob
SELECT * FROM "14";
INSERT INTO pob
SELECT * FROM "15_1";
INSERT INTO pob
SELECT * FROM "15_2";
INSERT INTO pob
SELECT * FROM "16";
INSERT INTO pob
SELECT * FROM "17";
INSERT INTO pob
SELECT * FROM "18";
INSERT INTO pob
SELECT * FROM "19";
INSERT INTO pob
SELECT * FROM "20";
INSERT INTO pob
SELECT * FROM "21";
INSERT INTO pob
SELECT * FROM "22";
INSERT INTO pob
SELECT * FROM "23";
INSERT INTO pob
SELECT * FROM "24";
INSERT INTO pob
SELECT * FROM "25";
INSERT INTO pob
SELECT * FROM "26";

INSERT INTO pob
SELECT * FROM "27";
INSERT INTO pob
SELECT * FROM "28_1";
INSERT INTO pob
SELECT * FROM "28_2";
INSERT INTO pob
SELECT * FROM "29";
INSERT INTO pob
SELECT * FROM "30_1";
INSERT INTO pob
SELECT * FROM "30_2";
INSERT INTO pob
SELECT * FROM "31";
INSERT INTO pob
SELECT * FROM "32";
INSERT INTO pob
SELECT * FROM "33_1";
INSERT INTO pob
SELECT * FROM "33_2";
INSERT INTO pob
SELECT * FROM "34";
INSERT INTO pob
SELECT * FROM "36";
INSERT INTO pob
SELECT * FROM "37";
INSERT INTO pob
SELECT * FROM "39";
INSERT INTO pob
SELECT * FROM "40";
INSERT INTO pob
SELECT * FROM "41";
INSERT INTO pob
SELECT * FROM "42";
INSERT INTO pob
SELECT * FROM "43";
INSERT INTO pob
SELECT * FROM "44";
INSERT INTO pob
SELECT * FROM "45";

INSERT INTO pob
SELECT * FROM "46_1";
INSERT INTO pob
SELECT * FROM "46_2";
INSERT INTO pob
SELECT * FROM "47";
INSERT INTO pob
SELECT * FROM "48";
INSERT INTO pob
SELECT * FROM "49";
INSERT INTO pob
SELECT * FROM "50";
INSERT INTO pob
SELECT * FROM "51";
INSERT INTO pob
SELECT * FROM "52";

ALTER TABLE "35"
  ALTER COLUMN geom TYPE geometry(MultiPolygon, 25830)
  USING ST_Transform(geom, 25830);
ALTER TABLE "38"
  ALTER COLUMN geom TYPE geometry(MultiPolygon, 25830)
  USING ST_Transform(geom, 25830);  
ALTER TABLE pob
  ALTER COLUMN geom TYPE geometry(MultiPolygon, 25830)
  USING ST_Transform(geom, 25830);

INSERT INTO pob
SELECT * FROM "35";
INSERT INTO pob
SELECT * FROM "38";

SELECT * FROM pob;

DROP TABLE IF EXISTS "01";
DROP TABLE IF EXISTS "02";
DROP TABLE IF EXISTS "03_1";
DROP TABLE IF EXISTS "03_2";
DROP TABLE IF EXISTS "04";
DROP TABLE IF EXISTS "05";
DROP TABLE IF EXISTS "06";
DROP TABLE IF EXISTS "07";
DROP TABLE IF EXISTS "08_1";
DROP TABLE IF EXISTS "08_2";
DROP TABLE IF EXISTS "09";
DROP TABLE IF EXISTS "10";
DROP TABLE IF EXISTS "11";
DROP TABLE IF EXISTS "12";
DROP TABLE IF EXISTS "13";
DROP TABLE IF EXISTS "14";
DROP TABLE IF EXISTS "15_1";
DROP TABLE IF EXISTS "15_2";
DROP TABLE IF EXISTS "16";
DROP TABLE IF EXISTS "17";
DROP TABLE IF EXISTS "18";
DROP TABLE IF EXISTS "19";
DROP TABLE IF EXISTS "20";
DROP TABLE IF EXISTS "21";
DROP TABLE IF EXISTS "22";
DROP TABLE IF EXISTS "23";
DROP TABLE IF EXISTS "24";
DROP TABLE IF EXISTS "25";
DROP TABLE IF EXISTS "26";

DROP TABLE IF EXISTS "27";
DROP TABLE IF EXISTS "28_1";
DROP TABLE IF EXISTS "28_2";
DROP TABLE IF EXISTS "29";
DROP TABLE IF EXISTS "30_1";
DROP TABLE IF EXISTS "30_2";
DROP TABLE IF EXISTS "31";
DROP TABLE IF EXISTS "32";
DROP TABLE IF EXISTS "33_1";
DROP TABLE IF EXISTS "33_2";
DROP TABLE IF EXISTS "34";
DROP TABLE IF EXISTS "36";
DROP TABLE IF EXISTS "37";
DROP TABLE IF EXISTS "39";
DROP TABLE IF EXISTS "40";
DROP TABLE IF EXISTS "41";
DROP TABLE IF EXISTS "42";
DROP TABLE IF EXISTS "43";
DROP TABLE IF EXISTS "44";
DROP TABLE IF EXISTS "45";

DROP TABLE IF EXISTS "46_1";
DROP TABLE IF EXISTS "46_2";
DROP TABLE IF EXISTS "47";
DROP TABLE IF EXISTS "48";
DROP TABLE IF EXISTS "49";
DROP TABLE IF EXISTS "50";
DROP TABLE IF EXISTS "51";
DROP TABLE IF EXISTS "52";
DROP TABLE IF EXISTS "35";
DROP TABLE IF EXISTS "38";